config/routes.rb
Rails.application.routes.draw do
  resources :proposals
  resources :communities
  resources :notices
  devise_for :domitories, :controller => "passwords => passwords"
  root  :to => "domitory#index"
  match ":controller(/:action(/:id))", :via => [:post, :get]
end

app/models/notice.rb
class Notice < ActiveRecord::Base
end

app/controllers/notices_controller.rb
class NoticesController < ApplicationController
  before_action :set_notice, only: [:show, :edit, :update, :destroy]

  # GET /notices
  # GET /notices.json
  include ApplicationHelper
  
  def index
    @current_page = if params[:current_page] then params[:current_page] else 1 end
    per_page = 15
    @notices = Notice.limit(per_page).order(id: :desc).all.offset((@current_page.to_i - 1) * per_page)
    @totalCnt = Notice.all.count
    @totalPageList = getTotalPageList(@totalCnt, per_page)
  end

  # GET /notices/1
  # GET /notices/1.json
  def show
    @notice.increment!(:notice_hits, 1)
  end

  # GET /notices/new
  def new
    @notice = Notice.new
    @notice.notice_hits = 0;
  end

  # GET /notices/1/edit
  def edit
  end

  # POST /notices
  # POST /notices.json
  def create
    @notice = Notice.new(notice_params)

    respond_to do |format|
      if @notice.save
        format.html { redirect_to @notice, notice: 'Notice was successfully created.' }
        format.json { render :show, status: :created, location: @notice }
      else
        format.html { render :new }
        format.json { render json: @notice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notices/1
  # PATCH/PUT /notices/1.json
  def update
    respond_to do |format|
      if @notice.update(notice_params)
        format.html { redirect_to @notice, notice: 'Notice was successfully updated.' }
        format.json { render :show, status: :ok, location: @notice }
      else
        format.html { render :edit }
        format.json { render json: @notice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notices/1
  # DELETE /notices/1.json
  def destroy
    @notice.destroy
    respond_to do |format|
      format.html { redirect_to notices_url, notice: 'Notice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_notice
      @notice = Notice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def notice_params
      params.require(:notice).permit(:notice_title, :notice_content, :notice_hits)
    end
end
 

app/helpers/notices_helper.rb
module NoticesHelper
    
end

app/views/notices/_form.html.erb
<div class="container">
	<div class="row">
  		<div class="panel">
  		  
        <br>
<%= form_for(@notice) do |f| %>
  <% if @notice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@notice.errors.count, "error") %> prohibited this notice from being saved:</h2>

      <ul>
      <% @notice.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
 <center>
<table class="type09">
  <thead>
    <tr>
      <th scope="cols" colspan = 2><center><h2>공지사항</h2></center></th>
    </tr>
  </thead>
  <tbody>
  <tr>
  <div class="field">
    <th scope="row"><center><%= f.label :제목 %></center></th>
    <td><%= f.text_field :notice_title, size:70 %></td>
  </div>
  </tr>
  <tr>
  <div class="field">
    <th scope="row" valign = "center"><center><%= f.label :내용 %></center></td>
    <td><%= f.text_area :notice_content, cols:80, rows:25 %></td>
  </div>
  </tr>
  </tbody>
</table>
</center>
<br>
<center>
  <div class="actions">
    <%= f.submit "등록", class: 'btn btn-default', align:"center" %>
  </div>
</center>
<% end %>
      </div>
  </div> 
</div>

app/views/notices/_linkto_main.html.erb
<%= link_to '메인으로', '/' %>

app/views/notices/edit.html.erb
<%= render 'linkto_main' %>
<h1>Editing Notice</h1>

<%= render 'form' %>

<%= link_to 'Show', @notice %> |
<%= link_to 'Back', notices_path %>

app/views/notices/index.html.erb
  <div class="container">
	<div class="row">
      <div class="col col-sm-12">
        
        <div class="panel">
        <div class="panel-body">
          모든 사생들은 필독해주세요 <span class="glyphicon glyphicon-heart-empty"></span>
        </div>
        </div>
        
      </div>
  	</div>
  </div>


<!-- Begin Body -->
<div class="container">
	<div class="row">
  		

              <div class="panel">
              

  <table class="type10">

  <thead>
    <tr align = "center">
      <th align = "center"><center>글번호</center></th>
      <th align = "center"><center>제목</center></th>
      <th><center>작성일</center></th>
      <th><center>조회수</center></th>
    </tr>
  </thead>

  <tbody>
    <% @notices.each do |notice| %>
      <tr align = "center">
        <td><%=notice.id %></td>
        <td><%= link_to notice.notice_title , notice %></td>
        <td><%= notice.created_at.strftime("%H:%M %Y/%m/%d") %></td>
        <td><%= notice.notice_hits %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<center>
<% @totalPageList.each do |page| %>
<a href="/notices?current_page=<%=page%>">
  [
<% if page == @current_page.to_i %>
<b><% end %>
<%= page %>
<% if page == @current_page.to_i %>
</b>
<% end %>
  ]
</a>
<% end %>
</center>
<br>
<% if current_domitory.email == "admin@dongduk.ac.kr" %>
<div style="text-align:right">
<a class="btn btn-default" href="<%= new_notice_path %>" role="button">글쓰기</a>
</div>
<% end %>
<hr>
             	</div>
      	</div> 
  	</div>

app/views/notices/new.html.erb
<%= render 'form' %>

app/views/notices/show.html.erb
<p id="notice"><%= notice %></p>


<% if current_domitory.email == "admin@dongduk.ac.kr" %>
<%= link_to '삭제', notice, method: :delete, data: { confirm: '삭제하시겠습니까?' } %>
<%= link_to '수정', edit_notice_path(@notice) %>
<% end %>
<%= link_to '목록으로', notices_path %>


<!-- Begin Body -->
<div class="container">
	<div class="row">
  		<div class="panel">
              
<table>
  <tr>
    <td>제목</td><td><%= @notice.notice_title %></td>
  </tr>
  <tr>
    <td>글쓴이</td><td>관리자</td>
  </tr>
  <tr>
    <td>내용</td><td><%= @notice.notice_content %></td>
  </tr>
</table>
             	</div>
      	</div> 
  	</div>