config/routes.rb
Rails.application.routes.draw do
  resources :proposals
  resources :communities
  resources :notices
  devise_for :domitories, :controller => "passwords => passwords"
  root  :to => "domitory#index"
  match ":controller(/:action(/:id))", :via => [:post, :get]
end

app/models/proposal.rb
class Proposal < ActiveRecord::Base
    has_many :reply_proposals
    validates :p_content,  :presence => true
    validates :p_category,  :presence => true
    validates :p_title, :presence => true
                        #,
                        #:length => { :minimum => 1 }
                        #모든 글(communitydb)은 내용(com_content)과 제목(com_title)을 가짐. 
                        #제목(com_title), 내용(com_content)은 최소 1글자 이상.
end

app/controllers/proposals_controller.rb
class ProposalsController < ApplicationController
  before_action :set_proposal, only: [:show, :edit, :update, :destroy]

  # GET /proposals
  # GET /proposals.json
  include ApplicationHelper
  
  def index
    @current_page = if params[:current_page] then params[:current_page] else 1 end
    per_page = 15
    @proposals = Proposal.limit(per_page).order(id: :desc).all.offset((@current_page.to_i - 1) * per_page)
    @totalCnt = Proposal.all.count
    @totalPageList = getTotalPageList(@totalCnt, per_page)
  end

  # GET /proposals/1
  # GET /proposals/1.json
  def show
  end

  # GET /proposals/new
  def new
    @proposal = Proposal.new
  end

  # GET /proposals/1/edit
  def edit
  end

  # POST /proposals
  # POST /proposals.json
  def create
    @proposal = Proposal.new(proposal_params)
    @proposal.p_answer = "No"
    @proposal.p_studentID = current_domitory.student_number
    respond_to do |format|
      if @proposal.save
        format.html { redirect_to @proposal, notice: '작성한 글이 게시판에 등록되었습니다.' }
        format.json { render :show, status: :created, location: @proposal }
      else
        format.html { render :new }
        format.json { render json: @proposal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /proposals/1
  # PATCH/PUT /proposals/1.json
  def update
    respond_to do |format|
      if @proposal.update(proposal_params)
        format.html { redirect_to @proposal, notice: '게시글이 수정되었습니다.' }
        format.json { render :show, status: :ok, location: @proposal }
      else
        format.html { render :edit }
        format.json { render json: @proposal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /proposals/1
  # DELETE /proposals/1.json
  def destroy
    @proposal.destroy
    respond_to do |format|
      format.html { redirect_to proposals_url, notice: '작성한 게시글이 삭제되었습니다.' }
      format.json { head :no_content }
    end
  end
  
  def write_answer
    @w_answer = ReplyProposal.new
    @w_answer.answer_studentID = current_domitory.student_number
    @w_answer.proposal_id  = params[:proposal_id]
    @w_answer.answer_content = params[:my_answer_content]
    @w_answer.save
    @edit_answer = Proposal.find_by_id(params[:proposal_id])
    @edit_answer.p_answer = "Yes"
    @edit_answer.save
    redirect_to :controller => 'proposals', :action => 'show', :id => params[:proposal_id]
  end
  
  def delete_answer
    @w_answer = ReplyProposal.find_by_id(params[:id])
    @w_answer.destroy
    @edit_answer = Proposal.find_by_id(params[:proposal_id])
    if @edit_answer.reply_proposals.count == 0
      @edit_answer.p_answer = "No"
    end
    @edit_answer.save
    redirect_to :controller => 'proposals', :action => 'show', :id => params[:proposal_id]
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_proposal
      @proposal = Proposal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def proposal_params
      params.require(:proposal).permit(:p_category, :p_answer, :p_title, :p_content)
    end
end

app/helpers/proposals_helper.rb
module ProposalsHelper
end

app/views/proposals/_form.html.erb
<div class="container">
	<div class="row">
  		<div class="panel">
  		  
        <br>
<%=form_for(@proposal) do |f| %>
  <% if @proposal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@proposal.errors.count, "error") %> prohibited this notice from being saved:</h2>

      <ul>
      <% @proposal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
<table class="type09">
  <thead>
    <tr>
      <th scope="cols" colspan = 2><center><h2>건의사항</h2></center></th>
    </tr>
  </thead>
  <tbody>
  <tr>
  <div class="field">
    <th scope="row" valign = "center"><%= f.label :분류 %></td>
    <td><%= f.select :p_category, [["질문"], ["수리요청"]] %></td>
  </div>
  </tr>
  <div class="field">
   <th scope="row"><center><%= f.label :제목 %></center></td>
    <td><%= f.text_field :p_title, size:70 %></td>
  </div>
  </tr>
  <tr>
  <div class="field">
    <th scope="row" valign = "center"><center><%= f.label :내용 %></center></td>
    <td><%= f.text_area :p_content, cols:80, rows:25 %></td>
  </div>
  </tr>
  <div class="field">
    <td ><% f.label :숨김 %></td>
    <td><%= f.hidden_field :p_studentID, :value => current_domitory.student_number %></td>
  </div>
  </tr>
</table>
  <div class="actions">
    <%= f.submit "확인", class: 'btn btn-default' %>
  </div>

<% end %>
      </div>
  </div> 
</div>

app/views/proposals/edit.html.erb
<%= render 'linkto_main' %>
<h1>수정하기</h1>

<%= render 'form' %>

<%= link_to 'Show', @proposal %> |
<%= link_to 'Back', proposals_path %>

app/views/proposals/index.html.erb
<div class="container">
	<div class="row">
      <div class="col col-sm-12">
        
        <div class="panel">
        <div class="panel-body">
          문의해주세요<span class="glyphicon glyphicon-heart-empty"></span>
        </div>
        </div>
        
      </div>
  	</div>
  </div>
<!-- Begin Body -->
<div class="container">
  <div class="panel" sty>
   <p id="notice"><%= notice %></p>

  <table class="table table-striped" style="margin-left:0px; margin-right:0px;">
  <thead>
    <tr align = "center">
      <td>글번호</td>
      <td colspan="2">분&nbsp;류</td>
      <td colspan="4">제&nbsp;목</td>
      <td>답변</td>
      <td colspan="2">작성일</td>
    </tr>
  </thead>

  <tbody>
    <% @proposals.each do |proposal| %>
      <tr align = "center">
        <td><%= proposal.id %></td>
        <td colspan="2"><%= proposal.p_category %></td>
        <td colspan="4"><%= link_to proposal.p_title, proposal %></td>
        <td><%= proposal.p_answer %></td>
        <td colspan="2"><%= proposal.created_at.strftime("%H:%M") %><br>
        <%= proposal.created_at.strftime("%Y/%m/%d") %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<center>
<br>
  <% @totalPageList.each do |page| %>
<a href="/proposals?current_page=<%=page%>">
  [
<% if page == @current_page.to_i %>
<b><% end %>
<%= page %>
<% if page == @current_page.to_i %>
</b>
<% end %>
  ]
</a>
<% end %>
</center>
<br>
<div style="text-align:right">
<a class="btn btn-default" href="<%= new_proposal_path %>" role="button">글쓰기</a>
</div>
<hr>
  </div>
</div>

app/views/proposals/new.html.erb
<%= render 'linkto_main' %>

<h1>새 글 쓰기</h1>

<%= render 'form' %>

<%= link_to 'Back', proposals_path %>

app/views/proposals/show.html.erb
<p id="notice"><%= notice %></p>
<%= render 'linkto_main' %>
<p>
  <strong>P category:</strong>
  <%= @proposal.p_category %>
</p>

<p>
  <strong>P answer:</strong>
  <%= @proposal.p_answer %>
</p>

<p>
  <strong>P title:</strong>
  <%= @proposal.p_title %>
</p>

<p>
  <strong>P content:</strong>
  <%= @proposal.p_content %>
</p>

<p>
  <strong>답글</strong><br>
  <% @proposal.reply_proposals.each do |r| %>
   >><%= r.answer_content %>
   <% if r.answer_studentID == current_domitory.student_number%>
        <form action="/proposals/delete_answer/<%= r.id %>" method="post">
           <input type="hidden" name="proposal_id" value="<%= r.proposal_id %>"/>
           <button type="submit" style="border: none; background: transparent;">삭제</button>
        </form>
    <%else%> <%end%>
  <%end%>
</p>

<p>
  <strong>답글 쓰기</strong><br>
    <form action="/proposals/write_answer" method="POST">
    <input type = "hidden" name="proposal_id" value="<%=@proposal.id%>">
    <textarea name="my_answer_content" rows="3" cols="15"></textarea>
    <input type = "submit" value="확인">
    </form>
</p>
 <% if @proposal.p_studentID == current_domitory.student_number%>
            <%= link_to '수정', edit_proposal_path(@proposal) %> |
            <%= link_to '삭제', @proposal, method: :delete, data: { confirm: '삭제하시겠습니까?' } %>
          <%else%> <%end%>
<%= link_to 'Back', proposals_path %>