config/routes.rb
Rails.application.routes.draw do
  resources :proposals
  resources :communities
  resources :notices
  devise_for :domitories, :controller => "passwords => passwords"
  root  :to => "domitory#index"
  match ":controller(/:action(/:id))", :via => [:post, :get]
end

app/models/community.rb
class Community < ActiveRecord::Base
    has_many :replies
    validates :com_content,  :presence => true
    validates :com_category,  :presence => true
    validates :com_title, :presence => true
                        #,
                        #:length => { :minimum => 1 }
                        #모든 글(communitydb)은 내용(com_content)과 제목(com_title)을 가짐. 
                        #제목(com_title), 내용(com_content)은 최소 1글자 이상.
end

app/controllers/communities_controller.rb
class CommunitiesController < ApplicationController
  before_action :set_community, only: [:show, :edit, :update, :destroy]

  # GET /communities
  # GET /communities.json
   include ApplicationHelper
  def index
    @current_page = if params[:current_page] then params[:current_page] else 1 end
    per_page = 15
    @communities = Community.limit(per_page).order(id: :desc).all.offset((@current_page.to_i - 1) * per_page)
    @totalCnt = Community.all.count
    @totalPageList = getTotalPageList(@totalCnt, per_page)
  end

  # GET /communities/1
  # GET /communities/1.json
  def show
    @community.increment!(:com_hits, 1)
  end

  # GET /communities/new
  def new
    @community = Community.new
    @community.com_hits = 0;
  end

  # GET /communities/1/edit
  def edit
  end

  # w_reply /communities
  # w_reply /communities.json
  def create
    @community = Community.new(community_params)
    @community.com_studentID = current_domitory.student_number
    respond_to do |format|
      if @community.save
        @community.update(:com_writer =>@community.id)
         @community.save
        format.html { redirect_to @community, notice: '작성한 글이 게시판에 등록되었습니다.' }
        format.json { render :notice, status: :created, location: @community }
      else
        format.html { render :new }
        format.json { render json: @community.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /communities/1
  # PATCH/PUT /communities/1.json
  def update
    respond_to do |format|
      if @community.update(community_params)
        format.html { redirect_to @community, notice: '게시글이 수정되었습니다.' }
        format.json { render :show, status: :ok, location: @community }
      else
        format.html { render :edit }
        format.json { render json: @community.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /communities/1
  # DELETE /communities/1.json
  def destroy
    @community.destroy
    respond_to do |format|
      format.html { redirect_to communities_url, notice: '작성한 게시글이 삭제되었습니다.' }
      format.json { head :no_content }
    end
  end
  
  def write_reply
    @w_reply = Reply.new
    @w_reply.r_studentID = current_domitory.student_number
    @w_reply.community_id  = params[:community_id]
    @w_reply.r_content = params[:my_r_content]
    @w_reply.save
    redirect_to :controller => 'communities', :action => 'show', :id => params[:community_id]
  end
  
  def delete_reply
    @w_reply = Reply.find_by_id(params[:id])
    @w_reply.destroy
    redirect_to :controller => 'communities', :action => 'show', :id => params[:community_id]
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_community
      if params[:id] == nil
      else
        @community = Community.find(params[:id])
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def community_params
      params.require(:community).permit(:com_category, :com_title, :com_content, :com_writer, :com_hits, :id)
    end
end

app/helpers/communities_helper.rb
module CommunitiesHelper
end

app/views/communities/_form.html.erb
<div class="container">
	<div class="row">
  		<div class="panel">
  		  
        <br>
<%= form_for (@community) do |f| %>
  <% if @community.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@community.errors.count, "error") %> <Br>게시물을 저장할 수 없습니다.</h2>

      <ul>
      <% @community.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<table class="type09">
  <thead>
    <tr>
      <th scope="cols" colspan = 2><center><h2>공지사항</h2></center></th>
    </tr>
  </thead>
  <tbody>
  <tr>
  <div class="field">
    <%= f.label :분류 %><br>
    <%= f.select :com_category, ['잡담', '벼룩시장', '요청']%>
  </div>
  <div class="field">
    <%= f.label :제목 %><br>
    <%= f.text_field :com_title%>
  </div>
  <div class="field">
    <%= f.label :내용 %><br>
    <%= f.text_area :com_content%>
  </div>
  <div class="field">
    <% f.label :글번호 %>
    <%= f.hidden_field :com_writer%>
    <% f.label :조회수%>
    <%= f.hidden_field :com_hits %>
    <%= f.hidden_field :com_studentID, value: current_domitory.student_number %>
  </div>
  <div class="actions">
    <%= f.submit "확인", class: 'btn btn-default'%>
  </div>
<% end %>
      </div>
  </div> 
</div>

app/views/communities/edit.html.erb
<%= render 'linkto_main' %>
<h1>수정하기</h1>

<%= render 'form' %>

<%= link_to '목록', @community %> |
<%= link_to '뒤로', communities_path %>

app/views/communities/index.html.erb
<div class="container">
	<div class="row">
      <div class="col col-sm-12">
        
        <div class="panel">
        <div class="panel-body">
          서로 상처받지 않도록 예의를 갖춰 소통합시다<span class="glyphicon glyphicon-heart-empty"></span>
        </div>
        </div>
        
      </div>
  	</div>
  </div>

<!-- Begin Body -->
<div class="container">
              <div class="panel">

          <p id="notice"><%= notice %></p>
          <center>

</center>

<table class="table table-striped">
  <thead>
    <tr align = "center">
      <td>글번호</td>
      <td>분 류</td>
      <td>제 목</td>
      <td>작성일</td>
      <td>조회수</td>
    </tr>
  </thead>

  <tbody>
    <% @communities.each do |community| %>
      <tr align = "center">
        <td><%= community.com_writer %></td>
        <td><%= community.com_category %></td>
        <td><%= link_to community.com_title, community %></td>
        <td><%= community.created_at.strftime("%H:%M %Y/%m/%d") %></td>
        <td><%= community.com_hits %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<center>
<% @totalPageList.each do |page| %>
<a href="/communities?current_page=<%=page%>">
  [
<% if page == @current_page.to_i %>
<b><% end %>
<%= page %>
<% if page == @current_page.to_i %>
</b>
<% end %>
  ]
</a>
<% end %>
</center>
<br>
<div style="text-align:right">
<a class="btn btn-default" href="<%= new_community_path %>" role="button">글쓰기</a>
</div>
<hr>
  	</div>
</div>

app/views/communities/new.html.erb
<%= render 'linkto_main' %>
<h1>작성하기</h1>

<%= render 'form' %>

<%= link_to '뒤로', communities_path %>

app/views/communities/show.html.erb
<p id="notice"><%= notice %></p>
<%= render 'linkto_main' %>
<p>
  <strong>분류</strong><br>
  <%= @community.com_category %>
</p>

<p>
  <strong>제목</strong><br>
  <%= @community.com_title %>
</p>

<p>
  <strong>글번호</strong>
  <%= @community.com_writer %>
  <strong>조회 수</strong>
  <%= @community.com_hits %>
</p>

<p>
  <strong>내용</strong><br>
  <%= @community.com_content %>
</p>

<p>
  <strong>댓글</strong><br>
  <% @community.replies.each do |r| %>
   >><%= r.r_content %>
    <% if r.r_studentID == current_domitory.student_number%>
        <form action="/communities/delete_reply/<%= r.id %>" method="post">
           <input type="hidden" name="community_id" value="<%= r.community_id %>"/>
           <button type="submit" style="border: none; background: transparent;">삭제</button>
        </form>
    <%else%> <%end%>
  <%end%>
</p>

<p>
  <strong>댓글 쓰기</strong><br>
    <form action="/communities/write_reply" method="POST">
    <input type = "hidden" name="community_id" value="<%=@community.id%>">
    <textarea name="my_r_content" rows="3" cols="15"></textarea>
    <input type = "submit" value="확인">
    </form>
</p>
<% if @community.com_studentID == current_domitory.student_number%>
            <%= link_to '수정|', edit_community_path(@community) %>
            <%= link_to '삭제', @community, method: :delete, data: { confirm: '삭제하시겠습니까?' } %>
<%else%> <%end%>

<%= link_to '뒤로', communities_path %>

app/views/communities/write_reply.erb
<%=@w_reply.r_content%>